version: '3'

services:

  postgres:
    image: postgis/postgis:14-3.4-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./dumps:/code/dumps
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
     image: redis:alpine
     ports:
        - '6379:6379'
