# Generated by Django 3.2.22 on 2023-10-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='special',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='service',
            field=models.ManyToManyField(blank=True, to='bank.Service'),
        ),
    ]
